#!/bin/sh

riverctl keyboard-layout pl
riverctl set-repeat 50 400

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

wlr-randr --output HDMI-A-1 --mode 1920x1080@74.973000Hz
wbg "${XDG_PICTURES_DIR:-$HOME/Pictures}/something.jpg" &

# General:
riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

riverctl map normal Super Return spawn foot
riverctl map normal Super B spawn firefox

riverctl map normal Super+Shift Return zoom
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super Space toggle-float

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Rivertile:
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Shift+Control H send-layout-cmd rivertile "main-location left"
riverctl map normal Super+Shift+Control J send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Shift+Control K send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Shift+Control L send-layout-cmd rivertile "main-location right"

# Mouse:
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Media keys:
riverctl map normal None Print spawn 'grim -g "$(slurp)" - | wl-copy && notify-send "Screenshot saved"'

for mode in normal locked
do
    riverctl map $mode None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
    riverctl map $mode None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 1"
    riverctl map $mode None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1"

    riverctl map $mode None XF86AudioNext spawn "playerctl next"
    riverctl map $mode None XF86AudioPlay spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev spawn "playerctl previous"
done

# Tags:
for i in $(seq 9)
do
    tag=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tag
    riverctl map normal Super+Shift $i set-view-tags $tag
    riverctl map normal Super+Control $i toggle-focused-tags $tag
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tag
done

scratch_tag=$((1 << 9))
riverctl map normal Super Minus toggle-focused-tags $scratch_tag
riverctl map normal Super+Shift Minus set-view-tags $scratch_tag

all_tags=$(((1 << 32) - ($scratch_tag + 1)))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Window rules:
riverctl rule-add -app-id "float*" float
